config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  get '/recruitment', to: 'pages#recruitment'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KP-Skills</title>
    <meta name="description" content="Un modeste cabinet de recrutement lyonnais par approche directe.">

    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="google-site-verification" content="c_4ptyu6RCPz7kaMlXl-84op3NFaDVpM7vJzbdmY6TI" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-154680414-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-154680414-1');
    </script>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media:"all" %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="p-0 m-0 min-w-full">
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="h-screen flex items-center bg-gray-800">
  <div class="flex flex-col mx-auto overflow-hidden text-center max-w-5xl p-24 px-4 sm:pt-12 sm:px-6 lg:pt-16">
    <h1 class="text-4xl tracking-tight font-extrabold text-white sm:text-5xl md:text-6xl">
      Nous aidons les<span class="text-aquamarine-500"> entrepreneurs</span> à <span class="text-aquamarine-500">recruter</span> les meilleurs talents et créer leurs <span class="text-aquamarine-500">site web</span>.
    </h1>
    <p class="mt-3 max-w-md mx-auto text-base text-gray-200 sm:text-lg md:mt-12 md:text-xl md:max-w-3xl">
      Choisissez votre univers
    </p>
    <div class="">
      <a class="btn m-4 btn-primary lg:mr-4 mr-0 lg:mb-0 mb-4" href="https://www.jeanro.dev/services">web development -></a>
      <%= link_to "recrutement ->", recruitment_path, class:"btn btn-primary outline lg:mr-4 m-4 lg:mb-0 " %>
    </div>
  </div>
</div>